server {
    listen 127.0.0.1:3300;
    client_max_body_size 20m;
    location / {
        proxy_pass http://[::1]:3302;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_buffering off;
        proxy_read_timeout 120s;
    }
}
server {
    listen 127.0.0.1:9090;
    client_max_body_size 100m;
    location / {
        proxy_pass http://[::1]:9092;
        proxy_set_header Host $http_host;
        proxy_buffering off;
    }
}
